# Generated by Django 3.2.4 on 2021-06-05 03:56

from django.db import migrations, models
from django.http import HttpResponse
import time, asyncio
from asgiref.sync import sync_to_async


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('ssd', models.CharField(max_length=255)),
            ],
        ),
    ]
