# Generated by Django 2.2.9 on 2020-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='memorial_meeting_only',
            field=models.BooleanField(default=False),
        ),
    ]
