# Generated by Django 2.2.9 on 2020-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200201_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='attending_full_week',
            field=models.BooleanField(default=True),
        ),
    ]
