# Generated by Django 2.2.9 on 2020-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_days', '0001_initial'),
        ('registration', '0004_registrant_attending_full_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='days_attending',
            field=models.ManyToManyField(blank=True, to='event_days.EventDay'),
        ),
    ]
