# Generated by Django 2.2.9 on 2020-02-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registrant_days_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='days_attending',
            field=models.ManyToManyField(blank=True, default=True, to='event_days.EventDay'),
        ),
    ]
