# Generated by Django 2.2.9 on 2020-02-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200201_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='attending_full_week',
        ),
    ]
