# Generated by Django 2.2.9 on 2020-02-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        ('registration', '0007_remove_registrant_attending_full_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='overnight_accommodations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accommodations.Accommodation'),
        ),
    ]
