# Generated by Django 2.2.9 on 2020-02-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_registrant_overnight_accommodations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='registration_cost',
        ),
    ]
