# Generated by Django 2.2.9 on 2020-02-15 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_myregistrantspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrants', to=settings.AUTH_USER_MODEL),
        ),
    ]
