# Generated by Django 2.2.9 on 2020-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20200222_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='registration_type',
            field=models.CharField(choices=[('overnight_attender', 'Overnight attender'), ('day_attender', 'Day attender'), ('memorials_only', 'Meeting for Memorials only')], default='overnight_attender', max_length=255),
        ),
    ]
