# Generated by Django 2.2.9 on 2020-03-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_registrant_registration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='attending_memorial_meeting_only',
        ),
    ]
