# Generated by Django 2.2.9 on 2020-11-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_remove_registrant_attending_memorial_meeting_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='days_attending',
            field=models.ManyToManyField(blank=True, default=True, help_text='On what day(s) will this registrant be attending the event?', to='event_days.EventDay'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='first_name',
            field=models.CharField(help_text='Registrant first name', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='last_name',
            field=models.CharField(help_text='Registrant last name', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='needs_ada_accessible_accommodations',
            field=models.BooleanField(help_text='Will this registrant need accessible accomodations, such as a wheelchair ramp?'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='overnight_accommodations',
            field=models.ForeignKey(blank=True, help_text='What type of overnight accommodations does this registrant need?', null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.AccommodationFee'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='registration_type',
            field=models.CharField(choices=[('overnight_attender', 'Overnight attender'), ('day_attender', 'Day attender'), ('memorials_only', 'Meeting for Memorials only')], default='overnight_attender', help_text="Select 'Overnight attender' if needing overnight accommodations, 'day attender' if commuting to the event daily, or 'Memorials only' if registrant will only attend the Meeting for Memorials.", max_length=255),
        ),
    ]
